// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import 'dotenv/config';               // Loads .env so DATABASE_URL is available
import { defineConfig } from 'prisma/config';

export default defineConfig({
  // Where your schema lives
  schema: 'prisma/schema.prisma',

  // Where migrations will be stored
  migrations: {
    path: 'prisma/migrations',
  },

  // Configure the datasource URL for Prisma CLI (migrate, etc.)
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
